### ISSUE TITLE
Unsubscribe problem - hitting firebase quota limits

### ISSUE THREAD

**Issue by sauntimo** [CSFrequency/react-firebase-hooks#111]
Hello, 

We're making use of this library quite a lot in our code, so first of all, thank you for all the work you've put in to it!

We seem to be having an issue with unsubscribing from collections. On our dashboard page in particular, which has a few hooks to fetch data for a few different components, requests to firebase seem to increase exponentially and if left open for a while, the tab will max out the 50k read limit on the free version on firebase (which we use in dev) which is obviously undesirable and suggests to me that we're adding multiple listeners without cleaning up ones which already exist.

We generally use `useCollection`, but also use `useDocument` in a couple of places. Similar to this;

```typescript
  const [exampleDocs, exampleLoading, exampleError] = useCollection(
    firestore
      .collection("example")
      .where(queryKey, opKey, id)
      .where("createdAt", ">=", example.start)
  );
```
I'm confused because;
- I've read the [firebase docs](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#onsnapshot) and I understand that `onSnapshot` returns a function to unsubscribe from changes
- I can see in the `react-firebase-hooks` [source](https://github.com/CSFrequency/react-firebase-hooks/blob/6be3e99356ea9221143d49247204e2aa85ba8202/firestore/useCollection.ts#L68) that this function is called listener and is returned wrapped in a function from the `useEffect` inside `useCollectionInternal`
- I understand from the [react docs](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1) that react should preform clean up from effects (using this returned function) on unmount *and* before the next render

So as far as I can tell, there's nothing wrong there. But it still feels like we're failing to unsubscribe properly. In fact today we've moved away from `useCollection` and `useDocument` to `useCollectionOnce` and `useDocumentOnce` throughout our codebase; it's a shame to lose real time data sync but until we can get a handle on this, it's better than maxing our db quota.

So my question is, have you come across any similar problems like this previously? Is there anything we need to be doing in our code to ensure that we avoid racking up multiple listeners on the same collection?

Very grateful for any any advice. Sorry I haven't shared much code, I wasn't sure what might be relevant, but I can add more if it's useful.

**Comment by mauriceackel** [comment]
Perhaps one thing you could try with your old configuration is to monitor the network usage in the browser's dev tools. I once had an issue where some broken logic for building a document reference lead to a constant recreation of the firestore document ref in each render. I think this happened as I dynamically created the document ref.

So you might wan't to check your code for instances where you pass a document ref to the hook that is created dynamical.
Something to watch out for are things like using `.map()` and similar when creating a document ref because this is recomputed on each render in my understanding. Eventually I fixed my problem by wrapping the corresponding code in a useMemo hook in order to return the docRef only if something changed with the dependencies. Then, I used the result from this hook to pass it to the react-firebase-hook function.

Having said that, I guess if this was you problem, you should see no improvement when using the `useDocumentOnce` hook, so this might not be your problem 😅

**Comment by sauntimo** [comment]
@mauriceackel I just wanted to say thank you for your comment - it seems you're right; after we switched to useOnce, the problem hadn't abated as you suggested might happen. I checked the network tab and there were many more requests than there should be, so it looks like our deps are changing when we're not expecting them too and our hooks are firing far more often than they should. I'm going to see if I can find the culprits and memoise them so that we only fire the hook when the values have definitely changed. Thanks for pointing me in the right direction! I'll close this question now.
