### ISSUE TITLE
best way to log errors in a centralised way

### ISSUE THREAD

**Issue by otusweb** [CSFrequency/react-firebase-hooks#136]
I'm using this library to interface with Firestore and it is great. 
The one thing I have not figured out (and that might be a feature request) is to be able to log errors to a service like sentry.io in a centralized way.

Right now, I end up adding this all over the place:
```

  React.useEffect(()=>{
    if (error != null)
    {
      logError(error, "my great message about the error")
    }
  }, [error])
```

I wonder if there is a centralized place where I could pass my log error method to have the firestore errors logged directly (even if I lose the custom message).

**Comment by chrisbianca** [comment]
@otusweb this is an interesting request. The sensible place would be for this functionality to be built into the Firebase client itself rather than into this hooks library. I had a quick search and it doesn't look like this is currently supported, so perhaps a feature request there would be useful?

In the meantime, I would propose that you break out the code again into a hook that you can re-use rather than copying the above chunk of code around, e.g.

```
export const useLogError = (error: string, msg: string) => {
  React.useEffect(()=>{
    if (error != null)
    {
      logError(error, "my great message about the error")
    }
  }, [error, msg])
}
```

Then you can simply call `useLogError(error, 'My error messages')` in your components instead.
