### ISSUE TITLE
OrderBy fails to work, without it works well.

### ISSUE THREAD

**Issue by Konstantin-Koktashev** [CSFrequency/react-firebase-hooks#159]
Hey There, I have this piece of code: 

  const [roomMessages, loading] = useCollection(
    roomId && db.collection('rooms').doc(roomId).collection('messages').orderBy('timestamp','asc')
  )

However the ordering at the end result in an empty array, without it works but but unordered.
is there a quick fix ? I get no console error's about indexing, just an empty array

**Comment by bartkoedijk** [comment]
I tried it locally and in my project .orderBy works fine. Once I had an issue with the .orderBy method and returned an empty array. The issue was that I added the wrong value in the orderBy method. So make sure every document in your "messages" collection contains a **fieldname** with "timestamp"

Hope it solves your problem =)

**Comment by Konstantin-Koktashev** [comment]
I did check, al 5 docs have timestamp, here a screenshot of the data:
[https://i.stack.imgur.com/TRPGh.png](url)

**Comment by bartkoedijk** [comment]
Your field is called **timeStamp** and in your query you set it as **timestamp**
In the where field it is case sensitive. :)

Can you change it to **timeStamp** in your where field and see if it works?

**Comment by Konstantin-Koktashev** [comment]
Well that does it, no idea how I missed that little detail, thx alot!
