### ISSUE TITLE
Type error for useCollectionData in version 4

### ISSUE THREAD

**Issue by fabarea** [CSFrequency/react-firebase-hooks#183]
Related to an old issue (https://github.com/CSFrequency/react-firebase-hooks/issues/120) but somehow different in the typescript error message. 

Here is the code 

```js
interface Task {
  title: string,
  message: string
  type: string
}

const [tasks, loading] = useCollectionData<Task>(
  collection(
    getFirestore(firebaseApp),
    'enterprises'
  )
);
```

I get the following typescript validation error

```
TS2345: Argument of type 'CollectionReference<DocumentData>' is not assignable to parameter of type 'Query<Task>'.   
Types of property 'converter' are incompatible.     
Type 'FirestoreDataConverter<DocumentData> | null' is not assignable to type 'FirestoreDataConverter<Task> | null'.       T
ype 'FirestoreDataConverter<DocumentData>' is not assignable to type 'FirestoreDataConverter<Task>'.        
 The types returned by 'fromFirestore(...)' are incompatible between these types.           
Type 'DocumentData' is not assignable to type 'Task'.
```

Version:

"react-firebase-hooks": "4.0.1"
"firebase": "^9",
"typescript": "~4.3"

**Comment by chrisbianca** [comment]
@fabarea Due to the way in which firebase v9 defines its types, it's no longer possible to cast directly, and instead you have to use the built in `FirebaseDataConverter` functionality. Take a look at the answer here for an example: https://github.com/CSFrequency/react-firebase-hooks/issues/180#issuecomment-962420543
