### ISSUE TITLE
useCollectionData return id as well

### ISSUE THREAD

**Issue by taylorchance** [CSFrequency/react-firebase-hooks#209]
It would be helpful to add an option that useCollectionData also returns the doc id as well.

**Comment by qwyzex** [comment]
Actually it's returning the document id in the previous version (I don't know which version start returning `undefined` id, but I use version 4.0.1 and it's returning the full document id!)

**Comment by chrisbianca** [comment]
As of `react-firebase-hooks` v5, the library relies on Firestore's built in [FirestoreDataConverter](https://firebase.google.com/docs/reference/js/firestore_.firestoredataconverter) functionality rather than the bespoke method used previously. This gives access to the underlying doc id and ref fields if required.

I've added an example to the docs here: https://github.com/CSFrequency/react-firebase-hooks/tree/master/firestore#transforming-data

Let me know if there are any issues

**Comment by LGR3VE** [comment]
@chrisbianca Thank you for the example in the docs. Do you have an example for JS, besides TS as well? I am struggling as well to include the Id by reading from the snapshot. Thank you so much!

**Comment by chrisbianca** [comment]
@LGR3VE the example for JS should be identically, you'll just need to drop the type annotations
