### ISSUE TITLE
Add useHttpsCallableData.

### ISSUE THREAD

**Issue by sanny-io** [CSFrequency/react-firebase-hooks#212]
`HttpsCallableResult` wraps the response in a `data` field. I am proposing a new function that directly returns the data contained in the `HttpsCallableResult`, kind of similar to the purpose of `useDocumentData`.

**Comment by chrisbianca** [comment]
@sanny-io Apologies for the delay on this one. Unlike with Firestore and the realtime database where a function needs to be called to extract the data, functions simply have a `data` field as you say, which makes it much easier to do this in the user's code. I'm inclined to leave this rather than add additional complexity into the library.
