### ISSUE TITLE
useList hooks throw away value of once

### ISSUE THREAD

**Issue by achuinard** [CSFrequency/react-firebase-hooks#74]
My component with a useList hook renders once for every child in a list. If I subscribe on a screen with 2,000 items this is very inefficient - my component re-renders 2,000 times. I think the hook should set the value of the data based on the once('value') and then be smart about handling childAdded. Does this make sense? Or am I doing something else wrong if my component is re-rendering once for every item in my list?

**Comment by caleb-harrelson** [comment]
The hook stores each child as an individual `DataSnapshot`, which is why it couldn't use the `once('value')` result (since only the root is a `DataSnapshot` and the children are the raw values). And even if it did use the value from `once`, `child_added` is still called once for every child which would cause re-renders.

I've addressed it by capturing the number of children from the `once` call, then using the `child_added` handler to collect an array of children equal to that size, and finally dispatching an event with that array to set the whole list. It has my "works on my machine" seal of approval :p
